services:
  streamlit:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - ./data:/app/data # Shared data directory between Streamlit and Superset
    # depends_on:
    #   - sqlite
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    command: streamlit run /app/data/app.py --server.port=8501 --server.address=0.0.0.0

  superset:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.superset
    ports:
      - "8088:8088"
    volumes:
      - ./:/app
      - ./data:/app/data
    command: superset run -p 8088 -h 0.0.0.0 --with-threads --reload --debugger
